### PR TITLE
PRSDM-3614: updated logic with the newlines for the quote block

### PR DESCRIPTION
**Pull request by WiaanB**

### CODE REVIEW

**Review by kmorake — APPROVED** [review]
LGTM

Not sure how to test it locally

**Review by Zalaras — COMMENTED** [review]
Never mind I thought this was in enterprise repo... ignore me

**Comment by CharlRitterDev** [comment]
@WiaanB if I remember correctly, on these repos if you merge to develop, it auto publishes a test version and if you merge to main it publishes the official new version.

Could we maybe get this into develop with a code review or 2, then with the test version someone else can do a local test and we can have a single review on dev->master?

**Review by CharlRitterDev — APPROVED** [review]
Codewise looks good, but would like to test locally if we could do an unofficial version

**Comment by zelrestemmet** [comment]
Since we're modifying the forked code now anyway, and the forked repo is pretty simple, would it not make sense to rather just add this code our `presidium-js-enterprise` repo? Like we're adding the embed plugins now?

Then we don't need to worry about maintaining this repo or build processes and ultimately we can get rid of this packages dependency.

**Pull request closed without merging**
